### ISSUE TITLE
jenkins service restart on each puppet run under Redhat 7

### ISSUE THREAD

**Issue by westbywest** [voxpupuli/puppet-jenkins#807] opened 2017-09-12 18:54 UTC
With commit 5ab2c8a8207f6351f59706255087c6eef32778d9 of this module, I get this on each puppet agent run, no matter if manual or invoked by the daemon:
```
puppet-agent[15850]: (/Service[jenkins]/ensure) ensure changed 'running' to 'stopped'
puppet-agent[15850]: (/Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/Transition[stop jenkins service]/enable) transition state {"ensure"=>"stopped"} applied to Service[jenkins]
puppet-agent[15850]: (/Stage[main]/Jenkins::Service/Service[jenkins]/ensure) ensure changed 'stopped' to 'running'
puppet-agent[15850]: (/Stage[main]/Jenkins::Service/Service[jenkins]) Unscheduling refresh on Service[jenkins]
```
The restarts don't occur using the v1.7.0 version of the module published to forge.

My machine:
- CentOS 7.3.1611
- OpenJDK 1.8.0_141
- Puppet agent 4.10.7

Module invocation:
```
  class { 'jenkins': }
```

Hiera:
```
jenkins::lts: false
jenkins::plugin_hash:
  ace-editor: {}
  ant: {}
  ... and dozens more plugins

```

**Comment by nick-george** [comment] 2017-10-29 01:43
I am running on the master branch and the same commit as @westbywest. I'm also running RHEL7 (OL7), with Jenkins version as below

```
Name        : jenkins
Arch        : noarch
Version     : 2.73.2
Release     : 1.1
Size        : 70 M
Repo        : installed
From repo   : jenkins

```
I get the following each time I run Jenkins. 
```
Notice: /Stage[main]/Profiles::Jenkins/Jenkins::User[jenkins]/Jenkins::Cli::Exec[create-jenkins-user-jenkins]/Exec[create-jenkins-user-jenkins]/returns: executed successfully
Info: /Stage[main]/Profiles::Jenkins/Jenkins::User[jenkins]/Jenkins::Cli::Exec[create-jenkins-user-jenkins]/Exec[create-jenkins-user-jenkins]: Scheduling refresh of Class[Jenkins::Cli::Reload]
Info: Class[Jenkins::Cli::Reload]: Scheduling refresh of Exec[reload-jenkins]
Notice: /Stage[main]/Profiles::Jenkins/Jenkins::Job[r10k-branch]/Jenkins::Job::Present[r10k-branch]/Exec[jenkins update-job r10k-branch]/returns: executed successfully
Info: /Stage[main]/Profiles::Jenkins/Jenkins::Job[r10k-branch]/Jenkins::Job::Present[r10k-branch]/Exec[jenkins update-job r10k-branch]: Scheduling refresh of Exec[reload-jenkins]
Notice: /Stage[main]/Profiles::Jenkins/Jenkins::Job[sync-elastic-repos]/Jenkins::Job::Present[sync-elastic-repos]/Exec[jenkins update-job sync-elastic-repos]/returns: executed successfully
Info: /Stage[main]/Profiles::Jenkins/Jenkins::Job[sync-elastic-repos]/Jenkins::Job::Present[sync-elastic-repos]/Exec[jenkins update-job sync-elastic-repos]: Scheduling refresh of Exec[reload-jenkins]
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]: Triggered 'refresh' from 3 events
```

**Comment by jhoblitt** [comment] 2017-11-14 00:52
The solution is to migrate to the native types.  `jenkins::job` and `jenkins::user` are not idempotent.

**Comment by nick-george** [comment] 2017-11-26 22:42
Thanks Joshua, 

Using the native types has fixed the jobs being re-installed on each run. However even using the native types, I have the same issue as OP on each run (a restart of Jenkins). 

Cheers, 
Nick

`Notice: /Service[jenkins]/ensure: ensure changed 'running' to 'stopped'
Notice: /Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/Transition[stop jenkins service]/enable: transition state {"ensure"=>"stopped"} applied to Service[jenkins]
Notice: /Stage[main]/Jenkins::Service/Service[jenkins]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Jenkins::Service/Service[jenkins]: Unscheduling refresh on Service[jenkins]
Notice: /Stage[main]/Profiles::Jenkins/Jenkins_security_realm[hudson.security.HudsonPrivateSecurityRealm]/arguments: arguments changed ['false', 'false', 'undef'] to 'false false '

**Comment by nick-george** [comment] 2017-11-29 21:41
After looking at the code, I believe it's this section in systemd.pp that forces Jenkins to stop on every run. In particular the ensure => stopped line. I think all Pascal did in his change was add a comma. I think @jhoblitt should be able to give us an indication why this needs to fire on every run. 

```
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 26)   transition { "stop ${service} service":
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 27)     resource   => Service[$service],
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 28)     attributes => {
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 29)       # lint:ignore:ensure_first_param
31743192 (Pascal Bourdier 2017-01-22 11:38:47 +0100 30)       ensure => stopped,
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 31)       # lint:endignore
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 32)     },
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 33)     prior_to   => [
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 34)       File[$sysv_init],
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 35)     ],
c66f0224 (Joshua Hoblitt  2016-12-30 09:05:48 -0700 36)   }
```

Having this happen on every puppet run is causing me major problems. 

Jenkins doesn't start fast enough on my system, so I get the following error: 
```
Notice: /Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/Transition[stop jenkins service]/enable: transition state {"ensure"=>"stopped"} applied to Service[jenkins]
Notice: /Stage[main]/Jenkins::Service/Service[jenkins]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Jenkins::Service/Service[jenkins]: Unscheduling refresh on Service[jenkins]
Error: Failed to apply catalog: Execution of '/bin/cat /usr/lib/jenkins/puppet_helper.groovy | /bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://localhost:8080 -i /var/lib/jenkins/.ssh/id_rsa -ssh -user jenkins groovy = user_info_all' returned 255: Nov 29, 2017 9:21:49 PM hudson.cli.SSHCLI sshConnection
WARNING: No header 'X-SSH-Endpoint' returned by Jenkins
```

Furthermore, it appears that any time there is a Jenkins CLI error, it causes the entire catalogue run to abort. I'm going to post this as a separate bug. 

Cheers, 
Nick

**Comment by jhoblitt** [comment] 2017-11-29 22:03
@nick-george Could you provide a minimal manifest to reproduce this? I don't see this in my own production env and it isn't occurring under the centos-7 acceptance tests.

**Comment by nick-george** [comment] 2017-12-01 03:17
I think I've figured it out. it's the resource defaults for file (in my case). I can reproduce it with: 

```
node default{
    File{
      ensure  => 'present',
      owner   => "jenkins",
      group   => "jenkins",
      mode    => '644',
    }
    class {'::jenkins':
    cli_ssh_keyfile    => "/var/lib/jenkins/.ssh/id_rsa",
    install_java       => false,
    configure_firewall => true,
    manage_user        => false,
    manage_group       => false,
    cli                => true,
    cli_username       => 'jenkins',
    cli_remoting_free  => true, #Force it to use the new CLI
    port               => 8080,  #Used by the Jenkins CLI only. Needs to be an int.
    config_hash        => {'JENKINS_PORT' => { 'value' => "8080"},
                           'HTTP_PORT' => { 'value' => "8080" }}, #This is required for the jenkins CLI which installs users etc.
  }
}
```

**Comment by jhoblitt** [comment] 2018-02-08 22:03
I'm going to close this our since there's not much we can do about resource defaults, which are pretty much a bag of razor blades.

**Closed by jhoblitt** 2018-02-08 22:03 UTC
