### ISSUE TITLE
Step /Jenkins::Cli/Exec[jenkins-cli] Fails on install

### ISSUE THREAD

**Issue by paulsmith47** [voxpupuli/puppet-jenkins#970] opened 2020-07-24 11:12 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.21
- Ruby: 2.4.10p364 (2020-03-31 revision 67879) [x86_64-linux]
- Distribution: Centos 7
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)

Add mod 'puppet-jenkins' to PuppetFile and run puppet apply

## What are you seeing

Installation fails at step:

```
/Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/
```

With error:

```
mv: cannot stat ‘WEB-INF/jenkins-cli.jar’: No such file or directory
Error: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]: Failed to call refresh: 'jar -xf /usr/lib/jenkins/jenkins.war WEB-INF/jenkins-cli.jar && mv WEB-INF/jenkins-cli.jar /usr/lib/jenkins/jenkins-cli.jar && rm -rf WEB-INF' returned 1 instead of one of [0]
Error: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]: 'jar -xf /usr/lib/jenkins/jenkins.war WEB-INF/jenkins-cli.jar && mv WEB-INF/jenkins-cli.jar /usr/lib/jenkins/jenkins-cli.jar && rm -rf WEB-INF' returned 1 instead of one of [0]
```

A quick google finds this rejected bug on jenkins issue queue suggesting this is the wrong file to reference and was intentionally removed from the 2.222.1 release

https://issues.jenkins-ci.org/browse/JENKINS-61717

## What behaviour did you expect instead

This module to install

## Output log

```
Notice: Scope(Class[Jenkins]): INFO: Using the automatic detection of new cli mode (See https://issues.jenkins-ci.org/browse/JENKINS-41745), use $::jenkins::cli_remoting_free=(true|false) to enable or disable explicitly
Notice: Compiled catalog for jenkins.puppet in environment production in 0.63 seconds
Info: Applying configuration version '1595585077'
Notice: /Stage[main]/Java/Package[java]/ensure: created
Notice: /Stage[main]/Java::Config/File_line[java-home-environment]/ensure: created
Notice: /Stage[main]/Jenkins::Repo::El/Yumrepo[jenkins]/ensure: created
Info: Yumrepo[jenkins](provider=inifile): changing mode of /etc/yum.repos.d/jenkins.repo from 600 to 644
Notice: /Stage[main]/Jenkins::Package/Package[jenkins]/ensure: created
Info: /Stage[main]/Jenkins::Package/Package[jenkins]: Scheduling refresh of Exec[jenkins-cli]
Notice: /Stage[main]/Jenkins::Config/File[/var/lib/jenkins/plugins]/ensure: created
Notice: /Stage[main]/Jenkins::Config/File[/var/lib/jenkins/jobs]/ensure: created
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Exec[force credentials.hpi-]/returns: executed successfully
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]/ensure: download archive from https://updates.jenkins.io/latest/credentials.hpi to /var/lib/jenkins/plugins/credentials.hpi  without cleanup
Info: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]: Scheduling refresh of Class[Jenkins::Service]
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/owner: owner changed 'root' to 'jenkins'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/group: group changed 'root' to 'jenkins'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/seltype: seltype changed 'user_tmp_t' to 'var_lib_t'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[structs]/Exec[force structs.hpi-]/returns: executed successfully
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[structs]/Archive[structs.hpi]/ensure: download archive from https://updates.jenkins.io/latest/structs.hpi to /var/lib/jenkins/plugins/structs.hpi  without cleanup
Info: /Stage[main]/Jenkins::Config/Jenkins::Plugin[structs]/Archive[structs.hpi]: Scheduling refresh of Class[Jenkins::Service]
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[structs]/File[/var/lib/jenkins/plugins/structs.hpi]/owner: owner changed 'root' to 'jenkins'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[structs]/File[/var/lib/jenkins/plugins/structs.hpi]/group: group changed 'root' to 'jenkins'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[structs]/File[/var/lib/jenkins/plugins/structs.hpi]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[structs]/File[/var/lib/jenkins/plugins/structs.hpi]/seltype: seltype changed 'user_tmp_t' to 'var_lib_t'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Sysconfig[JENKINS_JAVA_OPTIONS]/File_line[Jenkins sysconfig setting JENKINS_JAVA_OPTIONS]/ensure: created
Info: /Stage[main]/Jenkins::Config/Jenkins::Sysconfig[JENKINS_JAVA_OPTIONS]/File_line[Jenkins sysconfig setting JENKINS_JAVA_OPTIONS]: Scheduling refresh of Class[Jenkins::Service]
Notice: /Stage[main]/Jenkins::Config/Jenkins::Sysconfig[JENKINS_AJP_PORT]/File_line[Jenkins sysconfig setting JENKINS_AJP_PORT]/ensure: created
Info: /Stage[main]/Jenkins::Config/Jenkins::Sysconfig[JENKINS_AJP_PORT]/File_line[Jenkins sysconfig setting JENKINS_AJP_PORT]: Scheduling refresh of Class[Jenkins::Service]
Info: Class[Jenkins::Service]: Scheduling refresh of Service[jenkins]
Notice: /Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/File[/usr/lib/jenkins/jenkins-run]/ensure: defined content as '{md5}cf3541db48064c28b9145cd57969f7cb'
Info: /Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/File[/usr/lib/jenkins/jenkins-run]: Scheduling refresh of Service[jenkins]
Notice: /Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/Transition[stop jenkins service]/enable: transition state {"ensure"=>"stopped"} applied to Service[jenkins]
Info: Computing checksum on file /etc/init.d/jenkins
Info: /Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/File[/etc/init.d/jenkins]: Filebucketed /etc/init.d/jenkins to puppet with sum dd138cf0c94c82385eeb48138112a75c
Notice: /Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/File[/etc/init.d/jenkins]/ensure: removed
Notice: /Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/Systemd::Unit_file[jenkins.service]/File[/etc/systemd/system/jenkins.service]/ensure: defined content as '{md5}9957139e33fb3cc92573ebeb4f9cc4a7'
Info: /Stage[main]/Jenkins/Jenkins::Systemd[jenkins]/Systemd::Unit_file[jenkins.service]/File[/etc/systemd/system/jenkins.service]: Scheduling refresh of Class[Systemd::Systemctl::Daemon_reload]
Info: Class[Systemd::Systemctl::Daemon_reload]: Scheduling refresh of Exec[systemctl-daemon-reload]
Notice: /Stage[main]/Systemd::Systemctl::Daemon_reload/Exec[systemctl-daemon-reload]: Triggered 'refresh' from 1 event
Info: Systemd::Unit_file[jenkins.service]: Scheduling refresh of Service[jenkins]
Notice: /Stage[main]/Jenkins::Service/Service[jenkins]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Jenkins::Service/Service[jenkins]: Unscheduling refresh on Service[jenkins]
Notice: /Stage[main]/Jenkins::Cli/Exec[check-jenkins-cli]/returns: executed successfully
Info: /Stage[main]/Jenkins::Cli/Exec[check-jenkins-cli]: Scheduling refresh of Exec[jenkins-cli]
Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns: mv: cannot stat ‘WEB-INF/jenkins-cli.jar’: No such file or directory
Error: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]: Failed to call refresh: 'jar -xf /usr/lib/jenkins/jenkins.war WEB-INF/jenkins-cli.jar && mv WEB-INF/jenkins-cli.jar /usr/lib/jenkins/jenkins-cli.jar && rm -rf WEB-INF' returned 1 instead of one of [0]
Error: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]: 'jar -xf /usr/lib/jenkins/jenkins.war WEB-INF/jenkins-cli.jar && mv WEB-INF/jenkins-cli.jar /usr/lib/jenkins/jenkins-cli.jar && rm -rf WEB-INF' returned 1 instead of one of [0]
Notice: /Stage[main]/Jenkins::Cli/File[/usr/lib/jenkins/jenkins-cli.jar]: Dependency Exec[jenkins-cli] has failures: true
Warning: /Stage[main]/Jenkins::Cli/File[/usr/lib/jenkins/jenkins-cli.jar]: Skipping because of failed dependencies
Warning: /Stage[main]/Jenkins::Cli/Exec[safe-restart-jenkins]: Skipping because of failed dependencies
Info: Class[Jenkins::Cli]: Unscheduling all events on Class[Jenkins::Cli]
Warning: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]: Skipping because of failed dependencies
Warning: /Stage[main]/Jenkins::Cli_helper/File[/usr/lib/jenkins/puppet_helper.groovy]: Skipping because of failed dependencies
Warning: /Stage[main]/Jenkins/Anchor[jenkins::end]: Skipping because of failed dependencies
Info: Class[Jenkins]: Unscheduling all events on Class[Jenkins]
Info: Stage[main]: Unscheduling all events on Stage[main]
Notice: Applied catalog in 182.92 seconds
```

**Comment by ekohl** [comment] 2020-07-24 11:56
This was fixed in https://github.com/voxpupuli/puppet-jenkins/commit/189a6ecdde7c83e414155df108db17dd154b9113

**Comment by paulsmith47** [comment] 2020-07-24 11:56
Thanks, that is good to hear when can we expect a new release?

**Comment by ekohl** [comment] 2020-07-24 12:00
I'll refer to https://github.com/voxpupuli/puppet-jenkins/issues/966 but mention that we really need people to step up and maintain it.

**Comment by jonhattan** [comment] 2020-08-11 08:53
Duplicate of #967, #944, #945

**Closed** 2020-08-11 11:25 UTC
